# Generated by Django 3.2 on 2021-04-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210424_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalSupply',
        ),
    ]
