# Generated by Django 3.2 on 2021-05-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_delete_medicalsupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='total_beds',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
