# Generated by Django 3.2 on 2021-04-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210425_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='others',
        ),
    ]
