# Generated by Django 3.2 on 2021-04-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210425_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specify_other',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
