# Generated by Django 3.2 on 2021-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_specify_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specify_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
